### ISSUE TITLE
Sometimes the generated `$$fontBootstrap` is on the wrong order

### ISSUE THREAD

**Issue by peuter** [qooxdoo/qooxdoo-compiler#128]
example (from running `qx serve`):

```
qx.$$fontBootstrap['FASolid']={"size":40,"lineHeight":1,"family":["FASolid"],"sources":[{"family":"FASolid","source":["app/icons/fontawesome/fa-solid-900.ttf"]}]};
qx.$$fontBootstrap={};
qx.$$fontBootstrap['FARegular']={"size":40,"lineHeight":1,"family":["FARegular"],"sources":[{"family":"FARegular","source":["app/icons/fontawesome/fa-regular-400.ttf"]}]};
qx.$$fontBootstrap['FABrands']={"size":40,"lineHeight":1,"family":["FABrands"],"sources":[{"family":"FABrands","source":["app/icons/fontawesome/fa-brands-400.ttf","app/icons/fontawesome/fa-brands-400.woff"]}]};
```
and that obviously failes because the `$$fontBootstrap` object is used before its initialized.

Unfortunately this only happens from time to time, it seems to occur randomly

**Comment by cajus** [comment]
Are you sure that you're not using an outdated version of the compiler? There has been a problem in the past - where it only worked initially. That has been resolved by @johnspackman and I never saw that problem again.

**Comment by peuter** [comment]
The last time it happened is used the current git version from master branch. But maybe it was just a leftover from a former compilation. Will do a `qx clean` and see it it happens again. Closing this for now.

**Comment by peuter** [comment]
Sorry, but the error still occurs und current master, not as often as before but it is still happening from time to time

**Comment by cboulanger** [comment]
@peuter Is this still relevant?

**Comment by cboulanger** [comment]
No feedback for more than a month, closing.
