### ISSUE TITLE
qx resources doesn't seem to be copied over

### ISSUE THREAD

**Issue by cajus** [qooxdoo/qooxdoo-compiler#30]
If you create a new basic application from the Skeleton, you can see that the predefined theme tries to load a webfont that is part of the Indigo theme. This resource is not part of the generated source - and the path is wrong.

```
GET /source-output/foobar/qx/decoration/Indigo/font/JosefinSlab-SemiBold.woff HTTP/1.1" 404
```

**Comment by johnspackman** [comment]
fixed

**Comment by cajus** [comment]
I must be doing something wrong - or it's not fixed ;-)

Various resources (i.e. qx window open/close images or custom resources) are not copied. I've to do that manually.

**Comment by johnspackman** [comment]
please can you run just `qx` and check the version numbers?  They should be these:

```
john$ qx

qooxdoo command line interface
==============================
Versions: qooxdoo-cli v0.1.30, qooxdoo-compiler v0.1.26
```

If they're correct, please can you try `rm -rf source-output db.json resource-db.json` and try again.

**Comment by cajus** [comment]
I've the versions you mentioned above, and I've removed the files you've requested. The main problem is that the path seems to be wrong. This is the generated structure:

```
drwxrwxr-x 2 cajus cajus 4096  2. Nov 21:02 nogo
drwxrwxr-x 4 cajus cajus 4096  2. Nov 21:02 resource
drwxrwxr-x 5 cajus cajus 4096  2. Nov 21:02 transpiled
-rw-rw-r-- 1 cajus cajus    6  2. Nov 21:02 version.txt
```
where `nogo` is the application. When it's loaded, it tries to load *nogo/resources* (which is correct IMHO), but the generated output has it one level up.

**Comment by cajus** [comment]
Additionally the theming tries to load images that are not in the resources folder at all:

`http://localhost:3000/source/nogo/qx/decoration/Simple/window/minimize.gif`

**Comment by cajus** [comment]
I'll be off most of the day. Guess I'll just send you a tar-ball containing all of it when time allows.
